{
 "title": "StarRocks / Shared Data",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(up, job)" } },
   {
    "name": "fe_master",
    "query": {
     "query": "query_result(node_info{group=\"fe\", job=\"$cluster_name\", type=\"is_master\"})"
    }
   },
   {
    "name": "fe_instance",
    "query": {
     "query": "up{group=\"fe\", job=\"$cluster_name\"}"
    }
   },
   {
    "name": "be_instance",
    "query": {
     "query": "up{group=\"be\", job=\"$cluster_name\"}"
    }
   },
   { "name": "interval", "query": "1m,2m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Publish Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency / QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_publish_tablet_version_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_publish_tablet_version_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_publish_tablet_version_latency_9999{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Queued Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lake_publish_version_queued_tasks{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Tablet Metadata",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_get_tablet_metadata_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_get_tablet_metadata_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_get_tablet_metadata_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Put Tablet Metadata",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_put_tablet_metadata_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_put_tablet_metadata_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_put_tablet_metadata_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Get Txn Log",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_get_txn_log_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_get_txn_log_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_get_txn_log_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Put Txn Log",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "lake_put_txn_log_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_put_txn_log_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_put_txn_log_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    }
   ]
  },
  {
   "title": "Metacache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metacache Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lake_metacache_usage{job=\"$cluster_name\"} / lake_metacache_capacity{job=\"$cluster_name\"} * 100",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Delvec Cache Miss Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lake_delvec_cache_miss_minute{job=\"$cluster_name\"}"
      }
     ]
    },
    {
     "title": "Metadata Cache Miss Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lake_metadata_cache_miss_minute"
      }
     ]
    },
    {
     "title": "Txn Log Cache Miss Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "lake_txn_log_cache_miss_minute{job=\"$cluster_name\"}"
      }
     ]
    },
    {
     "title": "Segment Cache Miss Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "lake_segment_cache_miss_minute{job=\"$cluster_name\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vacuum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vacuum Deletes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_vacuum_del_file_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_vacuum_del_file_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_vacuum_del_file_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "lake_vacuum_del_file_fails{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} fails"
      }
     ]
    }
   ]
  }
 ]
}